language: python
matrix:
  include:
    - python: 3.6
      env: 
        - TOXENV=py36
      before_install:
        - python -m pip install --upgrade pip
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39

branches:
  only:
    - main

install:
  - pip install -U pip tox codecov

script: tox

after_success:
  - codecov
